import {
  Tent,
  Droplet,
  Droplets,
  Wheat,
  UtensilsCrossed,
  SquareParking,
  CreditCard,
  Mountain,
  CarFront,
  MapPin,
  Map as MapIcon,
  List as ListIcon,
  Zap,
  ShowerHead,
  Toilet,
  Trash2,
  Wifi,
  ShoppingCart,
  PawPrint,
  Sun,
  Star,
  Heart,
  CircleCheck,
  Flag,
  Shield,
  Settings,
  LogOut,
  Plus,
  Layers,
  Image as ImageIcon,
  X,
  ChevronLeft,
  ChevronRight,
  Pencil,
  Lock,
  TreePine,
  Users,
  Navigation,
  CircleUser,
  Mail,
  Music2,
  Clock,
  CircleX,
  Link as Link2,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  campsite: Tent,
  service_area: Droplet,
  farm_stay: Wheat,
  picnic_area: UtensilsCrossed,
  free_parking: SquareParking,
  paid_parking: CreditCard,
  wild_spot: Mountain,
  "4x4_spot": CarFront,
  water_point: Droplets,
  other: MapPin,
};

export const SERVICE_ICONS: Record<string, LucideIcon> = {
  service_water: Droplet,
  service_dump: Trash2,
  service_electricity: Zap,
  service_shower: ShowerHead,
  service_toilet: Toilet,
  service_wifi: Wifi,
  service_shop: ShoppingCart,
};

export function CategoryIcon({ category, ...props }: { category: string } & React.ComponentProps<LucideIcon>) {
  const Icon = CATEGORY_ICONS[category] || MapPin;
  return <Icon {...props} />;
}

export function ServiceIcon({ service, ...props }: { service: string } & React.ComponentProps<LucideIcon>) {
  const Icon = SERVICE_ICONS[service] || MapPin;
  return <Icon {...props} />;
}

export {
  Tent,
  Droplet,
  Droplets,
  Wheat,
  UtensilsCrossed,
  SquareParking,
  CreditCard,
  Mountain,
  CarFront,
  MapPin,
  MapIcon,
  ListIcon,
  Zap,
  ShowerHead,
  Toilet,
  Wifi,
  ShoppingCart,
  PawPrint,
  Sun,
  Star,
  Heart,
  CircleCheck,
  Flag,
  Shield,
  Settings,
  LogOut,
  Plus,
  Layers,
  ImageIcon,
  X,
  ChevronLeft,
  ChevronRight,
  Pencil,
  Trash2,
  Lock,
  TreePine,
  Users,
  Navigation,
  CircleUser,
  Mail,
  Music2,
  Clock,
  CircleX,
  Link2,
};
export type { LucideIcon };
